### ISSUE TITLE
Add Workbox-generated ServiceWorker?

### ISSUE THREAD

**Issue by moderndeveloperllc** [web-padawan/polymer3-webpack-starter#2]
@web-padawan I know this is more of a test repo, but you may want to look into adding a workbox-generated ServiceWorker to make this closer to a full PWA app - https://developers.google.com/web/tools/workbox/guides/generate-service-worker/webpack

Looks pretty straightforward. Thanks for putting together an example of a polymer-cli alternative.

**Comment by web-padawan** [comment]
Thanks for the suggestion! Yes, I was planning to add service worker setup. The app deployed to Heroku already has https for free, so it should work there. Will probably have to tweak express server config used here, to add support for https locally.

**Comment by web-padawan** [comment]
Fixed in d890433.

Note that we can use Service Workers on the localhost without https, as it is considered a secure origin. But still it is generated for production build only.

Many thanks to @Dabolus for his great work on this, I have reused the config from this repo:
https://github.com/Dabolus/polymer3-webpack-starter-kit/tree/master/conf/webpack
