### ISSUE TITLE
[Question] Load SVG Icons

### ISSUE THREAD

**Issue by titilambert** [web-padawan/polymer3-webpack-starter#7]
I'm trying to integrate font-awesome or MDI icons
I don't understand how to do that. I can not figure out how apply this:
https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself#using-svgs
in the polymer3 environment.
I try put it in the `index.html` but nothing happens.
So I don't know what to do :/
Thanks again for your help !

**Comment by web-padawan** [comment]
Using font-awesome is not straightforward with the Web Components, since it loads global CSS which does not apply inside of the Shadow DOM. You can workaround it by wrapping into [style module](https://www.polymer-project.org/2.0/docs/devguide/style-shadow-dom#style-modules) and there are components doing that, but they use Polymer 2: https://www.webcomponents.org/search/font-awesome

So one solution is to create Polymer 3 component yourself. But including all of the `font-awesome` icons is a huge impact on the bundle size, so I have a better proposal:

1. get only the SVG icons that you actually need in your app
2. use [gulp task](https://github.com/vaadin/vaadin-lumo-styles/blob/master/gulpfile.js#L87) to generate the `iron-iconset-svg` Polymer component
3. create another ES module file in the project, add that generated iconset there (maybe instead of this line: https://github.com/web-padawan/polymer3-webpack-starter/blob/208b47045f07d7575172c2478e6705522acf4702/src/app/starter-app.js#L12)
4. use `iron-icon` Polymer element, see https://github.com/web-padawan/polymer3-webpack-starter/blob/208b47045f07d7575172c2478e6705522acf4702/src/app/starter-app.js#L71

**Comment by titilambert** [comment]
Thanks for you long answer !
Is it easier with MDI icons ?
If not what is the icon set to use with Polymer 3 ?
Thanks !

**Comment by web-padawan** [comment]
You can use this tool to generate iconset with Material icons: https://poly-icon.appspot.com

Just remember to place it into ES module file, since Polymer 3 is not using HTML imports.

**Comment by johnthad** [comment]
I'll jump in and recommend this article if you want to convert font icons to SVG: https://www.sarasoueidan.com/blog/icon-fonts-to-svg/
